apiVersion: apps/v1
kind: Deployment
metadata:
  name: grpc-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grpc-server
  template:
    metadata:
      labels:
        app: grpc-server
    spec:
      containers:
        - name: grpc-server
          image: hsri/grpc-server:v1.0.0 #TODO
          ports:
            - containerPort: 50051
          env:
            - name: SUPABASE_DB
              valueFrom:
                configMapKeyRef:
                  name: supabase-config
                  key: SUPABASE_DB
            - name: SUPABASE_URL
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SUPABASE_URL
            - name: SUPABASE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: supabase-secrets
                  key: SUPABASE_API_KEY
          resources:  # ✅ Added CPU and Memory limits
            requests:
              memory: "128Mi"
              cpu: "250m"
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: grpc-server-service
spec:
  selector:
    app: grpc-server
  ports:
    - protocol: TCP
      port: 50051
      targetPort: 50051
  type: ClusterIP  # ✅ Exposing externally
