apiVersion: v1
kind: ConfigMap
metadata:
  name: supabase-config
data:
  # SUPABASE_DB: "postgresql://postgres:harsh@db.gxavtmhuulplbmbuesqi.supabase.co:5432/postgres"
  # SUPABASE_DB: "postgresql://postgres.gxavtmhuulplbmbuesqi:harsh@aws-0-ap-southeast-1.pooler.supabase.com:6543/postgres"

  SUPABASE_DB: "postgresql://postgres.wbqtckvzdlxlhvmrucrc:harsh@aws-0-ap-south-1.pooler.supabase.com:6543/postgres"
