apiVersion: v1
kind: Secret
metadata:
  name: supabase-secrets
type: Opaque
data:
  # SUPABASE_URL: aHR0cHM6Ly9neGF2dG1odXVscGxibWJ1ZXNxaS5zdXBhYmFzZS5jbw==
  # SUPABASE_API_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW1kNFlYWjBiV2gxZFd4d2JHSnRZblZsYzNGcElpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTXprNE56SXhNRFFzSW1WNGNDSTZNakExTlRRME9ERXdOSDAuMG9GcWF3RmN6Nk5Ub0xIQW1Id1N3VlViQXJuVzlNenBkcDkyN3JDV0doZw==

  SUPABASE_URL: aHR0cHM6Ly93YnF0Y2t2emRseGxodm1ydWNyYy5zdXBhYmFzZS5jbw==
  SUPABASE_API_KEY: ZXlKaGJHY2lPaUpJVXpJMU5pSXNJblI1Y0NJNklrcFhWQ0o5LmV5SnBjM01pT2lKemRYQmhZbUZ6WlNJc0luSmxaaUk2SW5kaWNYUmphM1o2Wkd4NGJHaDJiWEoxWTNKaklpd2ljbTlzWlNJNkltRnViMjRpTENKcFlYUWlPakUzTkRJek1qUTBPVGtzSW1WNGNDSTZNakExTnprd01EUTVPWDAuWVpfTFNSUllySjJxVFlZX25rRDd3NEZSRlEtM3pLUVluaEZhS18wSmY5Zw==